# Generated by Django 4.1.7 on 2024-08-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField()),
                ('api', models.CharField(help_text='API URL', max_length=1024)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='Response status code')),
                ('execution_time', models.DecimalField(decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'db_table': 'drf_api_logs',
            },
        ),
    ]
