# Generated by Django 4.1.7 on 2024-08-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Currency', models.CharField(default='EURO', help_text='Country currency.', max_length=30)),
                ('CurrencySymbol', models.CharField(default='€', help_text='Country currency Sym.', max_length=5)),
                ('SymbolRight', models.BooleanField(default=False, help_text='True if country is open to registration.')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='districtregion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('GPS_latitude', models.DecimalField(decimal_places=8, default=0, help_text='District central GPS latitude', max_digits=12)),
                ('GPS_longitude', models.DecimalField(decimal_places=8, default=0, help_text='District central GPS latitude', max_digits=12)),
                ('Name', models.CharField(help_text='Public events type', max_length=100, unique=True)),
                ('ZoomLevel', models.IntegerField(default=15, help_text='District Zoom Level')),
                ('GoogleCode', models.CharField(blank=True, default='', help_text='District Google Code', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'District/Region',
            },
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Public events type', max_length=30, unique=True)),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Image type', max_length=30, unique=True)),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Image requirements',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Code', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='localwifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Local wifi type', max_length=30, unique=True)),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Local Wi-Fi',
            },
        ),
        migrations.CreateModel(
            name='publicevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Public events type', max_length=30, unique=True)),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Public events',
            },
        ),
        migrations.CreateModel(
            name='RideDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.DurationField(default='00:30:00', help_text='HH:[MM]format', verbose_name='timeslot_duration')),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ride Duration',
            },
        ),
        migrations.CreateModel(
            name='sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Sound type', max_length=30, unique=True)),
                ('Token', models.CharField(default='', help_text='Token', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sound requirements',
            },
        ),
        migrations.CreateModel(
            name='time_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name', max_length=100)),
                ('TimeZone', models.CharField(help_text='TimeZone', max_length=100)),
                ('UTCoffset', models.DecimalField(decimal_places=0, default=0, help_text='UTC offset', max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'Time zones',
            },
        ),
        migrations.CreateModel(
            name='usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserTypeName', models.CharField(help_text='User Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='Endpoint name', max_length=50)),
                ('version', models.IntegerField(default=0, help_text='Version')),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date of version change')),
            ],
            options={
                'verbose_name_plural': 'Endpoint Version',
            },
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False, help_text='True if email was confirmed.')),
                ('Tele_confirmed', models.BooleanField(default=False, help_text='True if telephone was confirmed.')),
                ('is_blocked', models.BooleanField(default=True, help_text='True if user was is_blocked.')),
                ('Paymentupdated', models.BooleanField(default=True, help_text='True if user info was updated on Stripe.')),
                ('Language1', models.ForeignKey(blank=True, default='', help_text='Frist Language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_language1', to='core.language')),
                ('Language2', models.ForeignKey(blank=True, default='', help_text='Second Language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_language2', to='core.language')),
                ('PlantformUserType', models.ForeignKey(blank=True, default='', help_text='User type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_type', to='core.usertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userloginlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='IP', max_length=15)),
                ('user_agent', models.TextField(default='', help_text='User agent')),
                ('local', models.CharField(default='', help_text='Local', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('lon', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('geo_located', models.BooleanField(default=False, help_text='True if IP is geolocated.')),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now, help_text='Access Date.')),
                ('user', models.ForeignKey(blank=True, default='', help_text='payment_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User login log',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(help_text='Event Type', max_length=10)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('Request_Id', models.CharField(blank=True, help_text='Request ID', max_length=20)),
                ('Request', models.TextField(blank=True, help_text='The request', max_length=1000)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'API request',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Country Nome', max_length=100, unique=True)),
                ('PhoneCode', models.CharField(help_text='Country Phone Code', max_length=5, unique=True)),
                ('VAT', models.DecimalField(decimal_places=2, default=23.0, help_text='Country VAT', max_digits=5)),
                ('GPS_latitude', models.DecimalField(decimal_places=8, default=0, help_text='Country central GPS latitude', max_digits=12)),
                ('GPS_longitude', models.DecimalField(decimal_places=8, default=0, help_text='Country central GPS latitude', max_digits=12)),
                ('ZoomLevel', models.IntegerField(default=15, help_text='Country Zoom Level')),
                ('GoogleCode', models.CharField(blank=True, default='', help_text='Country Google Code', max_length=2)),
                ('Currency', models.ForeignKey(help_text='Country Currency', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('Language', models.ForeignKey(help_text='Country Language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
                ('time_zone', models.ForeignKey(help_text='Country time zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.time_zone')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        
        migrations.CreateModel(
            name='citymunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Service Municipality',default='', max_length=100, unique=True)),
                ('GPS_latitude', models.DecimalField(decimal_places=8, default=0, help_text='Municipality central GPS latitude', max_digits=12)),
                ('GPS_longitude', models.DecimalField(decimal_places=8, default=0, help_text='Municipality central GPS latitude', max_digits=12)),
                ('ZoomLevel', models.IntegerField(default=15, help_text='Municipality Zoom Level')),
                ('GoogleCode', models.CharField(blank=True, default='', help_text='Municipality Google Code', max_length=2)),
                ('districtregion', models.ForeignKey(help_text='Municipality District', on_delete=django.db.models.deletion.CASCADE, related_name='municipality_district', to='core.districtregion')),
            ],
            options={
                'verbose_name_plural': 'City/Municipality',
            },
        ),
    ]
