# Generated by Django 4.1.7 on 2024-09-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymunicipality',
            name='Name',
            field=models.CharField(default='', help_text='Service Municipality', max_length=100),
        ),
        migrations.AlterField(
            model_name='districtregion',
            name='Country',
            field=models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districtregion_country', to='core.country'),
        ),
        migrations.AlterField(
            model_name='districtregion',
            name='Name',
            field=models.CharField(default='', help_text='Service Disctrict', max_length=100),
        ),
    ]
