# Generated by Django 4.1.7 on 2024-09-26 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citymunicipality_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='commchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_opr', models.CharField(default='', help_text='Email address for RFQ & Replies to / from Suppliers of Streamers', max_length=50)),
                ('mail_api', models.CharField(default='', help_text='Email address for Tec-support for API Suppliers (vs Supl Streamers)', max_length=50)),
                ('mail_ride', models.CharField(default='', help_text='Email address for OPR Alerts & Comm between API (Suroga) & Clients API', max_length=50)),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date of registration or change')),
                ('Country', models.OneToOneField(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
            options={
                'verbose_name_plural': 'Communication Channels',
            },
        ),
    ]
