# Generated by Django 4.1.7 on 2024-08-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCategory', models.CharField(help_text='POC category', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Partners POC Categories',
            },
        ),
        migrations.CreateModel(
            name='profilepartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Partner Name', max_length=100)),
                ('Address', models.CharField(blank=True, help_text='Address', max_length=100)),
                ('Zip_Code', models.CharField(blank=True, help_text='Zip Code.', max_length=100)),
                ('City', models.CharField(blank=True, help_text='City', max_length=100)),
                ('Address_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('Telephone', models.CharField(blank=True, help_text='Business telephone.', max_length=100)),
                ('Telephone_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('ITIN', models.CharField(blank=True, help_text='Individual Tax Identification Number', max_length=40)),
                ('ITIN_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('IBAN', models.CharField(blank=True, help_text='Agency IBAN', max_length=40)),
                ('IBAN_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('HashKey', models.CharField(blank=True, help_text='Hash key to identity the partners agents', max_length=40)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('Website', models.URLField(blank=True, default='', help_text='Partner Website. ')),
                ('Google_play', models.URLField(blank=True, default='', help_text='APP in Google Play. ')),
                ('Google_play_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('Apple_store', models.URLField(blank=True, default='', help_text='APP in Apple Store. ')),
                ('Apple_store_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('Stripe_ID', models.CharField(blank=True, default='', help_text='Partner ID', max_length=10)),
                ('API_activated', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('API_test_mode', models.BooleanField(default=True, help_text='Test mode status TRUE=active/FALSE=inactive.')),
                ('API_integration_level', models.CharField(blank=True, default='', help_text='API integration level.', max_length=10)),
                ('APP_description', models.TextField(blank=True, help_text='JSON APP description.', max_length=1000)),
                ('APP_domain', models.URLField(blank=True, default='API calls', help_text='APP web domain')),
                ('APP_domain_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('webwooks_suroo', models.URLField(blank=True, default='', help_text='Webwook suroo alerts')),
                ('webwooks_suroo_verified', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('Payment_Policy', models.TextField(blank=True, help_text='JSON payment policy.', max_length=1000)),
                ('Observation', models.TextField(blank=True, help_text='Observation about client.', max_length=1000)),
                ('NumberRegisteredRides', models.IntegerField(default=0, help_text='Number registered rides')),
                ('NumberBookedRides', models.IntegerField(default=0, help_text='Number booked rides')),
                ('NumberCancedRides', models.IntegerField(default=0, help_text='Number of canced rides')),
                ('NumberCompletedRides', models.IntegerField(default=0, help_text='Number of completed rides')),
                ('Balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance', max_digits=7)),
                ('Validated_profile', models.BooleanField(default=False, help_text='API status TRUE=active/FALSE=inactive.')),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('Language', models.ForeignKey(blank=True, help_text='Language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='partnerpoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='ARepresentativegency Name', max_length=100)),
                ('Address', models.CharField(blank=True, help_text='Address', max_length=100)),
                ('Zip_Code', models.CharField(blank=True, help_text='Zip Code.', max_length=100)),
                ('email', models.CharField(blank=True, help_text='Business email.', max_length=50)),
                ('email_verified', models.BooleanField(default=False, help_text='True if email was verified')),
                ('Telephone', models.CharField(blank=True, help_text='Business telephone.', max_length=15)),
                ('HashKey', models.CharField(blank=True, help_text='Hash key to identity Representative', max_length=40)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('Extra_record', models.TextField(blank=True, help_text='JSON: extra records.', max_length=1000)),
                ('Observation', models.TextField(blank=True, help_text='Observation about Representative.', max_length=1000)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POC_category', to='partner.jobpoc')),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POC_Country', to='core.country')),
                ('Language1', models.ForeignKey(blank=True, help_text='POC_Language 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POC_Language1', to='core.language')),
                ('Language2', models.ForeignKey(blank=True, help_text='POC Language 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POC_Language2', to='core.language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POC_Agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Partner POCs',
            },
        ),
        migrations.CreateModel(
            name='coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(blank=True, help_text='Country', max_length=30)),
                ('DistrictRegion', models.CharField(blank=True, help_text='District/Region', max_length=30)),
                ('CityMunicipality', models.CharField(blank=True, help_text='City/Municipality', max_length=30)),
                ('ServiceCategory', models.ForeignKey(blank=True, help_text='Service type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.servicecategory')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'APP Coverage',
            },
        ),
    ]
