# Generated by Django 4.1.7 on 2024-08-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommTypeName', models.CharField(help_text='Communication Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Communication Types',
            },
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_Date_start', models.DateField(default=django.utils.timezone.now, help_text='contract Start')),
                ('Contract_Date_expiration', models.DateField(default=django.utils.timezone.now, help_text='contract Deadline')),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='True if contract is active')),
            ],
            options={
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='contractpaymenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentTypeName', models.CharField(help_text='Payment Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contract Payment Types',
            },
        ),
        migrations.CreateModel(
            name='contractpricetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceTypeName', models.CharField(help_text='Price Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contract Price Types',
            },
        ),
        migrations.CreateModel(
            name='contractsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequiredMaxConfigTime', models.DecimalField(decimal_places=1, default=0, help_text='Required Max Config Time (hours)', max_digits=5)),
                ('SectonStock', models.TextField(blank=True, help_text='JSON: Section stock description', max_length=1000)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='True if contract is active')),
                ('variante', models.TextField(blank=True, help_text='JSON: contract variant', max_length=1000)),
                ('CityMunicipality', models.ForeignKey(blank=True, help_text='City/Municipality', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_municipality', to='core.citymunicipality')),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_country', to='core.country')),
                ('DistrictRegion', models.ForeignKey(blank=True, help_text='District/Region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_district', to='core.districtregion')),
                ('contract', models.ForeignKey(blank=True, help_text='contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_contract', to='supplier.contract')),
            ],
            options={
                'verbose_name_plural': 'Contract Sections',
            },
        ),
        migrations.CreateModel(
            name='contracttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContratctTypeName', models.CharField(help_text='Contract Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contract Types',
            },
        ),
        migrations.CreateModel(
            name='identificationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Identification type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Identification Types',
            },
        ),
        migrations.CreateModel(
            name='informationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(help_text='Information type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Information Types',
            },
        ),
        migrations.CreateModel(
            name='offertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(help_text='Offer type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Offer Types',
            },
        ),
        migrations.CreateModel(
            name='profileagency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Agency Name', max_length=100)),
                ('Address', models.CharField(blank=True, help_text='Address', max_length=100)),
                ('Zip_Code', models.CharField(blank=True, help_text='Zip Code.', max_length=100)),
                ('Telephone', models.CharField(blank=True, help_text='Business telephone.', max_length=100)),
                ('ITIN', models.CharField(blank=True, help_text='Individual Tax Identification Number', max_length=40)),
                ('IBAN', models.CharField(blank=True, help_text='Agency IBAN', max_length=40)),
                ('HashKey', models.CharField(blank=True, editable=False, help_text='Hash key to identity Agency', max_length=40)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Website', models.URLField(blank=True, default='', help_text='Agency Website. ')),
                ('Stripe_ID', models.CharField(blank=True, default='', help_text='Agency ID', max_length=10)),
                ('Extra_record', models.TextField(blank=True, help_text='JSON: extra records.', max_length=1000)),
                ('Observation', models.TextField(blank=True, help_text='Observation about Agency.', max_length=1000)),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_Country', to='core.country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agency profile',
            },
        ),
        migrations.CreateModel(
            name='reprecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobCategory', models.CharField(help_text='Representative category', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Representative category',
            },
        ),
        migrations.CreateModel(
            name='requisitiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requistion', models.CharField(help_text='Requisition type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Requisition type',
            },
        ),
        migrations.CreateModel(
            name='selectiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(help_text='selection type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Selection Types',
            },
        ),
        migrations.CreateModel(
            name='servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Service name', max_length=50, unique=True)),
                ('ContractA', models.BooleanField(default=False, help_text='True if requires type A contract')),
                ('ContractB', models.BooleanField(default=False, help_text='True if requires type B contract')),
                ('ContractC', models.BooleanField(default=False, help_text='True if requires type C contract')),
                ('ContractD', models.BooleanField(default=False, help_text='True if requires type D contract')),
                ('ContractE', models.BooleanField(default=False, help_text='True if requires type E contract')),
                ('ContractF', models.BooleanField(default=False, help_text='True if requires type F contract')),
                ('ServiceRules', models.TextField(blank=True, help_text='JSON: Service rules', max_length=1000)),
                ('ServiceSetting', models.TextField(blank=True, help_text='JSON: Service rules', max_length=1000)),
                ('Duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Duration', to='core.rideduration')),
                ('Equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Image', to='core.equipment')),
                ('Image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Image', to='core.image')),
                ('LocalWifi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Wifi', to='core.localwifi')),
                ('PublicEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Event', to='core.publicevent')),
                ('Sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_Sound', to='core.sound')),
            ],
            options={
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_API', models.BooleanField(default=False, help_text='Agency has an API')),
                ('API_tested', models.BooleanField(default=False, help_text='API was tested')),
                ('API_ID', models.CharField(blank=True, help_text='API key', max_length=50, unique=True)),
                ('WebSite', models.CharField(blank=True, help_text='API root page', max_length=50, unique=True)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of protocol creation or update')),
                ('Agency', models.ForeignKey(help_text='Agency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_agency', to=settings.AUTH_USER_MODEL)),
                ('type_identification', models.ForeignKey(help_text='Identification type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_identification', to='supplier.identificationtype')),
                ('type_information', models.ForeignKey(help_text='Information type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_information', to='supplier.informationtype')),
                ('type_offer', models.ForeignKey(help_text='Offer type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_offer', to='supplier.offertype')),
                ('type_requisition', models.ForeignKey(help_text='Requisition type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_requisition', to='supplier.requisitiontype')),
                ('type_selection', models.ForeignKey(help_text='Selection type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_selectionr', to='supplier.selectiontype')),
            ],
            options={
                'verbose_name_plural': 'Protocol',
            },
        ),
        migrations.CreateModel(
            name='profilerepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='ARepresentativegency Name', max_length=100)),
                ('Address', models.CharField(blank=True, help_text='Address', max_length=100)),
                ('Zip_Code', models.CharField(blank=True, help_text='Zip Code.', max_length=100)),
                ('Telephone', models.CharField(blank=True, help_text='Business telephone.', max_length=15)),
                ('HashKey', models.CharField(blank=True, editable=False, help_text='Hash key to identity Representative', max_length=40)),
                ('Registration', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Extra_record', models.TextField(blank=True, help_text='JSON: extra records.', max_length=1000)),
                ('Observation', models.TextField(blank=True, help_text='Observation about Representative.', max_length=1000)),
                ('Agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Agency', to='supplier.profileagency')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_category', to='supplier.reprecategory')),
                ('Country', models.ForeignKey(blank=True, help_text='Country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_country', to='core.country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Representative profile',
            },
        ),
        migrations.CreateModel(
            name='contractsectionchannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommInvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_comm5', to='supplier.profilerepresentative')),
                ('CommOrderSaToSupp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_comm3', to='supplier.profilerepresentative')),
                ('CommOrderSuppToSa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_comm4', to='supplier.profilerepresentative')),
                ('CommPaymConfirm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_comm6', to='supplier.profilerepresentative')),
                ('CommRideSuppToSa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_comm2', to='supplier.profilerepresentative')),
                ('ContractSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_section', to='supplier.contractsection')),
            ],
            options={
                'verbose_name_plural': 'Contract Section Channels',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='Contract_POC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_POC', to='supplier.profilerepresentative'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_payment', to='supplier.contractpaymenttype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='supplier.contractpricetype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_type', to='supplier.contracttype'),
        ),
    ]
