# Generated by Django 4.1.7 on 2025-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NUTSRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('nuts0', models.CharField(max_length=2, verbose_name='Country Code')),
                ('nuts1', models.CharField(max_length=3, verbose_name='Major Socio-Economic Region')),
                ('nuts2', models.CharField(max_length=4, verbose_name='Basic Region for Policies')),
                ('nuts3', models.CharField(max_length=5, verbose_name='Small Regions')),
            ],
            options={
                'verbose_name_plural': 'NUTS Regions',
            },
        ),
        migrations.RemoveField(
            model_name='contractsection',
            name='CityMunicipality',
        ),
        migrations.RemoveField(
            model_name='contractsection',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='contractsection',
            name='DistrictRegion',
        ),
        migrations.AddField(
            model_name='contractsection',
            name='nuts0',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Country (NUTS 0)'),
        ),
        migrations.AddField(
            model_name='contractsection',
            name='nuts1',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Major Region (NUTS 1)'),
        ),
        migrations.AddField(
            model_name='contractsection',
            name='nuts2',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Policy Region (NUTS 2)'),
        ),
        migrations.AddField(
            model_name='contractsection',
            name='nuts3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Small Region (NUTS 3)'),
        ),
        migrations.AddIndex(
            model_name='nutsregion',
            index=models.Index(fields=['postal_code', 'country_code'], name='supplier_nu_postal__5cab24_idx'),
        ),
        migrations.AddIndex(
            model_name='nutsregion',
            index=models.Index(fields=['nuts0'], name='supplier_nu_nuts0_5d2802_idx'),
        ),
        migrations.AddIndex(
            model_name='nutsregion',
            index=models.Index(fields=['nuts1'], name='supplier_nu_nuts1_f524c8_idx'),
        ),
        migrations.AddIndex(
            model_name='nutsregion',
            index=models.Index(fields=['nuts2'], name='supplier_nu_nuts2_34c193_idx'),
        ),
        migrations.AddIndex(
            model_name='nutsregion',
            index=models.Index(fields=['nuts3'], name='supplier_nu_nuts3_d7724d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nutsregion',
            unique_together={('postal_code', 'country_code')},
        ),
    ]
