# Generated by Django 4.1.7 on 2024-08-21 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kit_Ref_Numer', models.CharField(help_text='Kit Ref number', max_length=15, unique=True)),
                ('Content', models.TextField(blank=True, help_text='JSON: kit content', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Kit Stock',
            },
        ),
        migrations.CreateModel(
            name='kittype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KitTypeName', models.CharField(help_text='Kit Type Name', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kit Types',
            },
        ),
        migrations.CreateModel(
            name='operationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationTypeName', models.CharField(help_text='Operation Type', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Operation Types',
            },
        ),
        migrations.CreateModel(
            name='operationlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(help_text='Operation description', max_length=100, unique=True)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ExpectedArrivalDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ConfirmationFromSectionA', models.BooleanField(default=False, help_text='True if supplier confirmed kit arrivel.')),
                ('DeliveryFromSectionD', models.BooleanField(default=False, help_text='True if supplier confirmed kit delivery.')),
                ('ReceptionFromSectionD', models.BooleanField(default=False, help_text='True if supplier confirmed kit reception.')),
                ('ContractSectionA', models.ForeignKey(help_text='Contract A', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_A', to='kit.operationtype')),
                ('ContractSectionD', models.ForeignKey(help_text='Contract D', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_De', to='kit.operationtype')),
                ('Kit', models.ForeignKey(help_text='Kit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_kit', to='kit.kitstock')),
                ('OperationType', models.ForeignKey(help_text='Operation Type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_type', to='kit.operationtype')),
            ],
            options={
                'verbose_name_plural': 'Operation Log',
            },
        ),
        migrations.AddField(
            model_name='kitstock',
            name='KitType',
            field=models.ForeignKey(help_text='Kite type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kit.kittype'),
        ),
        migrations.AddField(
            model_name='kitstock',
            name='Location',
            field=models.ForeignKey(blank=True, help_text='Location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.contractsection'),
        ),
    ]
